const ActivitiesCardsData = {
  section: {
    title: "Our Adventure Packages",
    subtitle:
      "River & Rock Adventure offers Ganga rafting routes and Rishikesh bungee experiences — pick your thrill, book with confidence.",
  },
  categories: [
    {
      id: "rafting",
      label: "River Rafting Packages",
      badge: "Rafting",
      tagline: "Choose your Ganga route — from gentle family rides to 70 km expeditions.",
      accent: "red",
      metaLabel: "Route distance",
      items: [
        {
          id: "raft-1",
          title: "Club House / NIM Beach",
          price: "Rs. 600 /-",
          priceLabel: "Per Person",
          meta: "09 Kms",
          description: "A short, gentle stretch — ideal for families and first-time rafters.",
          image: "/Images/ActivitiesImages/12Km.png",
        },
        {
          id: "raft-2",
          title: "Brahmpuri to Ram Jhula",
          price: "Rs. 800 /-",
          priceLabel: "Per Person",
          meta: "12 Kms",
          description: "Scenic rapids with steady waves and beautiful Ganga views.",
          image: "/Images/ActivitiesImages/12Km.png",
        },
        {
          id: "raft-3",
          title: "Shivpuri / NIM Beach",
          price: "Rs. 1200 /-",
          priceLabel: "Per Person",
          meta: "16 Kms",
          description: "Popular route with exciting rapids and full safety support.",
          image: "/Images/ActivitiesImages/16Km.png",
        },
        {
          id: "raft-4",
          title: "Marine Drive / NIM Beach",
          price: "Rs. 2200 /-",
          priceLabel: "Per Person",
          meta: "25 Kms",
          description: "Longer journey through Marine Drive with stronger rapids.",
          image: "/Images/ActivitiesImages/24Km.png",
        },
        {
          id: "raft-5",
          title: "Kaudiyala / NIM Beach",
          price: "Rs. 3500 /-",
          priceLabel: "Per Person",
          meta: "35 Kms",
          description: "Premium route with bold rapids and deep Himalayan gorges.",
          image: "/Images/ActivitiesImages/24Km.png",
        },
        {
          id: "raft-6",
          title: "Devprayag Expedition (2N/3D)",
          price: "Rs. 20,000 /-",
          priceLabel: "Per Person",
          meta: "70 Kms",
          description: "Multi-day expedition with camping, meals, and 70 km of raw river.",
          image: "/Images/ActivitiesImages/24Km.png",
        },
      ],
    },
    {
      id: "bungee",
      label: "Bungee & Adventure Jump Packages",
      badge: "Bungee",
      tagline: "Cliff jumps, giant swings, and valley ziplines over Rishikesh.",
      accent: "yellow",
      metaLabel: "Jump type",
      items: [
        {
          id: "bungee-1",
          title: "Standard Bungee Jump",
          price: "Rs. 3,500 /-",
          priceLabel: "Per Person",
          meta: "83 Meters",
          description: "India's iconic fixed-platform jump with certified instructors and harness gear.",
          image: "/Images/IllustrationImages/CardIllustrationImage.png",
        },
        {
          id: "bungee-2",
          title: "Giant Swing",
          price: "Rs. 3,000 /-",
          priceLabel: "Per Person",
          meta: "High Swing",
          description: "Arc through the valley on a giant pendulum swing above the Ganga gorge.",
          image: "/Images/IllustrationImages/ActivitiesBackground.jpg",
        },
        {
          id: "bungee-3",
          title: "Flying Fox (Zipline)",
          price: "Rs. 1,500 /-",
          priceLabel: "Per Person",
          meta: "Valley Line",
          description: "Soar across the valley on a guided zipline with panoramic river views.",
          image: "/Images/IllustrationImages/CardIllustrationImage.png",
        },
        {
          id: "bungee-4",
          title: "Bungee + Swing Combo",
          price: "Rs. 5,500 /-",
          priceLabel: "Per Person",
          meta: "Combo",
          description: "The ultimate adrenaline duo — bungee jump and giant swing in one booking.",
          image: "/Images/IllustrationImages/ActivitiesBackground.jpg",
        },
      ],
    },
  ],
};

export default ActivitiesCardsData;
