const ActivitiesCardsData = {
  section: {
    title: "Our Adventure Packages",
    subtitle:
      "River & Rock Adventure offers Ganga rafting routes and Rishikesh bungee experiences — pick your thrill, book with confidence.",
  },
  categories: [
    {
      id: "rafting",
      label: "River Rafting Packages",
      badge: "Rafting",
      tagline: "Choose your Ganga route — from gentle family rides to 70 km expeditions.",
      accent: "red",
      metaLabel: "Route distance",
      items: [
        {
          id: "raft-1",
          title: "Club House / NIM Beach",
          price: "Rs. 600 /-",
          priceLabel: "Per Person",
          meta: "09 Kms",
          image: "/Images/ActivitiesImages/12Km.png",
          highlights: ["Life Jackets Included", "Certified River Guide", "Family Friendly"],
        },
        {
          id: "raft-2",
          title: "Brahmpuri to Ram Jhula",
          price: "Rs. 800 /-",
          priceLabel: "Per Person",
          meta: "12 Kms",
          image: "/Images/ActivitiesImages/12Km.png",
          highlights: ["Safety Kayak Support", "Certified River Guide", "Scenic Ganga Route"],
        },
        {
          id: "raft-3",
          title: "Shivpuri / NIM Beach",
          price: "Rs. 1200 /-",
          priceLabel: "Per Person",
          meta: "16 Kms",
          image: "/Images/ActivitiesImages/16Km.png",
          highlights: ["Grade II–III Rapids", "Certified River Guide", "Most Popular Route"],
        },
        {
          id: "raft-4",
          title: "Marine Drive / NIM Beach",
          price: "Rs. 2200 /-",
          priceLabel: "Per Person",
          meta: "25 Kms",
          image: "/Images/RaftingImages/Marine-Drive-rafting.jpg",
          highlights: ["Longer River Stretch", "Stronger Rapids", "Safety Gear Included"],
        },
        {
          id: "raft-5",
          title: "Kaudiyala / NIM Beach",
          price: "Rs. 3500 /-",
          priceLabel: "Per Person",
          meta: "35 Kms",
          image: "/Images/RaftingImages/Kaudiyala-rafting.jpg",
          highlights: ["Premium Rapids", "Deep Gorge Views", "Expert Safety Crew"],
        },
        {
          id: "raft-6",
          title: "Devprayag Expedition (2N/3D)",
          price: "Rs. 20,000 /-",
          priceLabel: "Per Person",
          meta: "70 Kms",
          image: "/Images/ActivitiesImages/24Km.png",
          highlights: ["Camping Included", "Meals Included", "70 Km Expedition"],
        },
      ],
    },
    {
      id: "bungee",
      label: "Bungee & Adventure Jump Packages",
      badge: "Bungee",
      tagline: "Cliff jumps over Rishikesh — normal and freestyle jumps with DSLR video.",
      accent: "yellow",
      metaLabel: "Jump height",
      items: [
        {
          id: "bungee-1",
          title: "117m Himalayan Bungee Jump",
          price: "Rs. 5,000 /-",
          priceLabel: "Per Person",
          meta: "117m",
          image: "/Images/BungeeActivityImages/Himalayan_Bungee_117.webp",
          jumpStyle: "normal",
          highlights: ["DSLR Video Included", "117m Jump Height"],
        },
        {
          id: "bungee-2",
          title: "111m Himalayan Bungee Jump",
          price: "Rs. 4,000 /-",
          priceLabel: "Per Person",
          meta: "111m",
          image: "/Images/BungeeActivityImages/Himalayn_Freestyle_bungee_111M.webp",
          jumpStyle: "freestyle",
          highlights: ["DSLR Video Included", "111m Jump Height"],
        },
        {
          id: "bungee-3",
          title: "109m Splash Bungee Jump",
          price: "Rs. 3,600 /-",
          priceLabel: "Per Person",
          meta: "109m",
          image: "/Images/BungeeActivityImages/Splash_109m_Bungee.jpeg",
          jumpStyle: "freestyle",
          highlights: ["DSLR Video Included", "109m Splash Jump"],
        },
        {
          id: "bungee-4",
          title: "85m Bungee Jump",
          price: "Rs. 2,500 /-",
          priceLabel: "Per Person",
          meta: "85m",
          image: "/Images/BungeeActivityImages/Splash_85m_bungee.jpeg",
          jumpStyle: "freestyle",
          highlights: ["DSLR Video Included", "85m Jump Height"],
        },
      ],
    },
  ],
};

export default ActivitiesCardsData;
